### ISSUE TITLE
When the node exceeds 1000 +, it takes a long time to remove the node. Can you optimize it? thank you!

### ISSUE THREAD

**Issue by wanglujiu** [sgratzl/cytoscape.js-layers#3]
Here's an example
https://codepen.io/wlhz/pen/XWaeOry

**Comment by sgratzl** [comment]
you can use the `queryEachTime: true` renderPerNode option see https://github.com/sgratzl/cytoscape.js-layers/blob/bdac7762dfd420b97849b9ccff0346f262a82857/src/elements/common.ts#L2-L21

to force that the list of nodes will be queried each time. This has the side effect that instead of position/add/removal the plugin will listen to render events of cytoscape. Thus only rendering one update instead of rendering each node removal individually.

**Comment by wanglujiu** [comment]
> you can use the `queryEachTime: true` renderPerNode option see
> 
> https://github.com/sgratzl/cytoscape.js-layers/blob/bdac7762dfd420b97849b9ccff0346f262a82857/src/elements/common.ts#L2-L21
> 
> to force that the list of nodes will be queried each time. This has the side effect that instead of position/add/removal the plugin will listen to render events of cytoscape. Thus only rendering one update instead of rendering each node removal individually.

That's OK. Thank you very much!
